name: CI

on:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - main
      - ci-auth

jobs:
  auth:
    name: CI test with auth
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: "3.x"

    - name: Install keyring
      run: python3 -m pip install .

    - uses: chainguard-dev/setup-chainctl@be0acd273acf04bfdf91f51198327e719f6af978 # v0.4.0
      with:
        identity: TODO

    - name: Use keyring to install private packages
      run: python3 -m pip install --index-url https://libraries.cgr.dev/python/simple/ ansi
