name: CI

on:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  auth:
    name: CI test with auth
    permissions:
      contents: read
      id-token: write # Needed to get auth
    runs-on: ubuntu-latest

    env:
      CHAINGUARD_IDENTITY: ce2d1984a010471142503340d670612d63ffb9f6/04af60cc28fb08b7

    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.x"

    - name: Install keyring
      run: python3 -m pip install .

    - uses: chainguard-dev/setup-chainctl@c125f765e82b09a42af3185f3214465314d75c5d # v0.5.0
      with:
        identity: ${{ env.CHAINGUARD_IDENTITY }}
    - run: chainctl auth login --audience=libraries.cgr.dev --identity=${{ env.CHAINGUARD_IDENTITY }}

    - name: Use keyring to install private packages
      run: python3 -m pip install --index-url https://libraries.cgr.dev/python/simple/ ansi
